#!/bin/bash

# Fix screen terminfo to support italics
create_terminfo_screen_it()
{
	# Create custom terminfo from screen-256color to support italics
	if [[ ! -f "$HOME/.terminfo/s/screen-256color-it" ]]; then
		mkdir -p $HOME/.terminfo
		infocmp screen-256color | sed \
			-e 's/^screen[^|]*|[^,]*,/screen-256color-it|screen with italics support,/' \
			-e 's/%?%p1%t;3%/%?%p1%t;7%/' \
			-e 's/smso=[^,]*,/smso=\\E[7m,/' \
			-e 's/rmso=[^,]*,/rmso=\\E[27m,/' \
			-e '$s/$/ sitm=\\E[3m, ritm=\\E[23m,/' \
			> /tmp/terminfo
		tic /tmp/terminfo
	fi
}

# Pick up a better terminal with italics support
case "$TERM" in
	xterm*)
		if infocmp rxvt-unicode-256color >/dev/null 2>&1; then
			export TERM=rxvt-unicode-256color
		fi
		;;
	screen*)
		create_terminfo_screen_it
		if infocmp screen-256color-it >/dev/null 2>&1; then
			export TERM=screen-256color-it
		elif infocmp screen-256color >/dev/null 2>&1; then
			export TERM=screen-256color
		fi
		;;
esac


exe_name=`basename ${BASH_SOURCE[0]}`

# Find and launch first suitable real executable
for p in ${PATH//:/$'\n'}; do
	[[ -x "$p/$exe_name" ]] || continue
	[[ "$p/$exe_name" == ${BASH_SOURCE[0]} ]] && continue
	exec "$p/$exe_name" "$@"
done
