#!/bin/bash

# This is to enable true colors in tmux
# Test with tmux info | grep Tc

# If tmux hasn't started yet, start a new server instance
# Customize it (with true color support)
# And attach to it immediately
if [[ -z "$TMUX" && $# -eq 0 ]]; then
	/usr/bin/tmux new-session -d
	/usr/bin/tmux set-option -ga terminal-overrides ",xterm-256color:Tc"

	if [[ -z "$PS1" ]]; then
		exec /usr/bin/tmux attach
	fi
else
	# Otherwise just pass through to the program
	exec /usr/bin/tmux "$@"
fi
