#!/bin/bash

set -e

[[ -x /usr/bin/yaourt ]] || exit 255

/usr/bin/yaourt "$@"

if [[ ${1:0:2} == -S && $1 != "-Ss" ]]; then
    if ! ycm-check.sh ; then
        echo "Updating outdated YouCompleteMe deployment"
        ycm-update.sh
        echo "Validation"
        ycm-check.sh
    fi
fi
