#!/bin/bash -e

comma=''

add_opt()
{
    echo "$1" >> .ccls
    echo -n "$comma'$1'" >>.ycm_extra_conf.py
    comma=', '
}

cat > .ccls <<END
clang++
END

cat >.ycm_extra_conf.py <<END
def Settings( **kwargs ):
  return {
END
echo -n "    'flags': [ " >>.ycm_extra_conf.py

add_opt "-xc++"
add_opt "-std=c++17"

echo \
    | clang -v -E -x c++ - 2>&1 \
    | awk '/#include <...>/,/End of search/' \
    | while read -r l; do
        [[ -d "$l" ]] && add_opt "-isystem`readlink -f $l`" || true
    done

echo ' ],' >>.ycm_extra_conf.py
echo '  }' >>.ycm_extra_conf.py
