#!/bin/bash

set -e

[[ -x /usr/bin/pacaur ]] || exit 255

/usr/bin/pacaur "$@"

if [[ $1 == -S || $1 =~ -S.*u.* ]]; then
    white=`tput setaf 7`
    blue=`tput setaf 4`
    bold=`tput bold`
    reset=`tput sgr 0`
    echo "${bold}${blue}:: ${white}Checking YouCompleteMe deployment...${reset}"
    if ! ycm-check.sh ; then
        echo "Updating outdated YouCompleteMe deployment"
        ycm-update.sh
        echo "Validation"
        ycm-check.sh
    fi

    # Upgrading libraries may leave AUR packages broken.
    # Let's loop over all installed "foreign" packages, check their linkage
    # with ldd and rebuild those with dangling dependency.
    echo "${bold}${blue}:: ${white}Checking whether AUR packages need be rebuilt...${reset}"
    to_rebuild=
    for pkg in `pacaur -Qm | awk '{print $1}'`; do
        # Blacklist: skip known exceptional packages
        grep -q $pkg <<END && continue
jdk
javafx-scenebuilder
END
        echo "  Checking $pkg"
        for f in `pacaur -Ql $pkg | grep -E '/(bin|lib)/.' | awk '{print $2}'`; do
            if [[ -x "$f" ]]; then
                output=$(ldd $f 2>/dev/null || continue)
                if grep -q 'not found' <<< "$output"; then
                    to_rebuild="$to_rebuild $pkg"
                    break
                fi
            fi
        done
    done

    if [[ -n "$to_rebuild" ]]; then
        /usr/bin/pacaur -S $to_rebuild
    fi
fi
