#!/bin/bash

set -e

[[ -x /usr/bin/pacaur ]] || exit 255

/usr/bin/pacaur "$@"

if [[ $1 == -S || $1 =~ -S.*u.* ]]; then
    white=`tput setaf 7`
    blue=`tput setaf 4`
    bold=`tput bold`
    reset=`tput sgr 0`
    echo "${bold}${blue}:: ${white}Checking YouCompleteMe deployment...${reset}"
    if ! ycm-check.sh ; then
        echo "Updating outdated YouCompleteMe deployment"
        ycm-update.sh
        echo "Validation"
        ycm-check.sh
    fi

    if pacaur -Qi rtags-git >/dev/null 2>&1; then
        echo "${bold}${blue}:: ${white}Checking rtags-git...${reset}"
        if ldd /usr/bin/rdm | grep "not found" >/dev/null 2>&1; then
            echo "Updating rtags-git"
            pacaur -S rtags-git
        fi
    fi
fi
