#!/bin/bash

launched_by_bitbake()
{
	pid=$$
	echo "pid=$pid"

	while [[ $pid != 1 ]]; do
		pid=`ps -p $pid -o ppid= 2>/dev/null`
		comm=`ps -p $pid -o comm= 2>/dev/null`
		pid=`echo $pid`  # Trim
		echo "pid=$pid comm=$comm"

		[[ "$comm" == "bitbake" ]] && return 0
	done

	return 1
}

launched_by_bitbake && exit 0

set -e
PATH="/usr/local/bin:$PATH"
trap "rm -f .git/tags.$$" EXIT
ctags --tag-relative -Rf.git/tags.$$ --exclude=.git --exclude=test --languages=-javascript,sql
mv .git/tags.$$ .git/tags
